import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

let migraUruguayLinks: string[] = [
  'migration/panama/visa-de-transito',
  'migration/uruguay/consulado-uruguay-en-cuba/legalizacion-documentos',
  'migration/uruguay/consulado-uruguay-en-cuba/reunificacion-familiar'
];

let migraPanamaLinks: string[] = [
  'migration/panama/visa-de-transito'
]

const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //migrateSidebar: [{type: 'autogenerated',dirName: 'migra'}],
  //businessSidebar: [{type: 'autogenerated', dirName: 'business'}],
  // But you can create a sidebar manually

  migrateSidebar: [
    {
      type: 'category',
      label: 'Migración',
      description: "Todos los temas migratorios en un sólo lugar",
      items: ['migration/intro',   
        {type: 'category',label: 'Panamá', items: migraPanamaLinks},
        {type: 'category',label: 'Uruguay', items: migraUruguayLinks}
      ],
    },
  ],
  businessSidebar: [
    {
      type: 'category',
      label: 'Negocios',
      items: ['business/intro',
        {type: 'category',label: 'Bitcoin',items: ['business/bitcoin/intro']},
        {type: 'category',label: 'Monedas',items: ['business/currencies/intro']}
      ]
    }
  ],
  ocioSidebar: [
    {
      type: 'category',
      label: 'Ocio',
      items: ['leisure/intro',
        {type: 'category',label: 'Salidas',items: ['leisure/goingout/intro']}
      ]

    }
  ],
  otherSidebar: [
    {
      type: 'category',
      label: 'Otros',
      items: ['others/intro']
    }
  ]

};

export default sidebars;
